export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDIENTS_FAILD = 'FETCH_INGREDIENTS_FAILD';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';

export const PURCHASE_ORDER_START = 'PURCHASE_ORDER_START';
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS';
export const PURCHASE_ORDER_FAIL = 'PURCHASE_ORDER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';
export const PURCHASE_BURGER = 'PURCHASE_BURGER';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';
export const FETCH_ORDER = 'FETCH_ORDER';

export const DELETE_ORDER = 'DELETE_ORDER';
export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL';
export const DELETE_ORDER_HANDLER = 'DELETE_ORDER_HANDLER';

export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const CHECK_AUTH_TIMEOUT = 'CHECK_AUTH_TIMEOUT';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
